### ISSUE TITLE
Crash on .exe

### ISSUE THREAD

**Issue by Desinformao** [nacrt/SkyblockClient#6]
wen i try to install the skyclient the exe stop work, in the log i have that 

errorAt: InitializeComponent(); unkown fatal error initizialing installer 
Provide value on 'System.Windows.Markup.StaticResourceHolder' threw an exception.
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at SkyblockClient.MainWindow..ctor()

maybe you can help me

**Comment by nacrt** [comment]
We don't support Windows 7 anymore
